project/urls.py
from django.contrib import admin
from django.urls import path
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('adoptPets/', views.adoptPets, name="adoptData"),
    path('lostPets/', views.lostPets, name="lostData"),
    path('fancyCard/', views.fancyCard),
    path('dogBreed/', views.dogBreed),
    path('upload/', views.upload, name="upload"),
    path('uploadLost/', views.uploadLost, name="uploadLost"),
    path('analysisBreed/', views.analysisBreed),
    path('analysis/', views.analysis),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/models.py
from django.db import models

class Adopt(models.Model):
    species = models.CharField(max_length=50)
    breed = models.CharField(max_length=50)
    sex = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    age = models.CharField(max_length=50)
    ligation = models.CharField(max_length=50)
    vaccine  = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    pic = models.CharField(max_length=250)
    picUpload = models.ImageField(null=True,blank=True,upload_to="images/")
    def ___str__(self):
        return self.breed

class Lost(models.Model):
    name = models.CharField(max_length=50)
    variety = models.CharField(max_length=50)
    species = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)
    body = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    age = models.CharField(max_length=50)
    lostdate  = models.DateField()
    area = models.CharField(max_length=50)
    pet_jpg = models.CharField(max_length=250)
    picUpload = models.ImageField(null=True,blank=True,upload_to="images/")
    def ___str__(self):
        return self.name

mysite/views.py
from django.shortcuts import render
from plotly.offline import plot
from mysite.models import Lost,Adopt
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from .form import AdoptForm,LostForm
from django.core.files.storage import FileSystemStorage

def index(request):
    return render(request, "index.html", locals())

def adoptPets(request):
    if request.method == "POST":
        keywords = request.POST.get("keywords")
        adoptPets = Adopt.objects.filter(breed__contains=keywords)
        # .order_by('-id')
    else :
        adoptPets = Adopt.objects.all()

    p = Paginator(adoptPets,12)
    page = request.GET.get('page')
    adopts = p.get_page(page)

    speciesInDataBase = Adopt.objects.values('species').distinct()
    breedsInDataBase = Adopt.objects.values('breed').distinct()
    return render(request, "adoptPets.html", locals())

def lostPets(request):
    if request.method == "POST":
        keywords = request.POST.get("keywords")
        lostPets = Lost.objects.filter(species__contains=keywords)
    else :
        lostPets = Lost.objects.all()

    p = Paginator(lostPets,12)
    page = request.GET.get('page')
    losts = p.get_page(page)

    speciesInDataBase = Lost.objects.values('species').distinct()

    return render(request, "lostPets.html", locals())

def fancyCard(request):
    lostPets = Lost.objects.all()
    return render(request, "fancyCard.html", locals())

def dogBreed(request):
    return render(request, "dogBreed.html", locals())

def upload(request):
    submitted = False
    if request.method == "POST":
        form = AdoptForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/upload?submitted=True')
    else :
        form = AdoptForm
        if 'submitted' in request.GET:
            submitted = True
    form = AdoptForm

    adoptPets = Adopt.objects.all()
    p = Paginator(adoptPets,12)
    page = request.GET.get('page')
    adopts = p.get_page(page)

    return render(request, "upload.html", locals())

def uploadLost(request):
    submitted = False
    if request.method == "POST":
        form = LostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/uploadLost?submitted=True')
    else :
        form = AdoptForm
        if 'submitted' in request.GET:
            submitted = True
    form = LostForm

    lostPets = Lost.objects.all()
    p = Paginator(lostPets,12)
    page = request.GET.get('page')
    losts = p.get_page(page)

    return render(request, "uploadLost.html", locals())

def analysisBreed(request):
    return render(request, "analysisBreed.html", locals())

def analysis(request):
    return render(request, "analysis.html", locals())

templates/adoptPets.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
  <div class="row align-items-center">
  <form action="{% url 'adoptData' %}" class="d-flex mt-2 justify-content-end" method="POST">
    {% csrf_token %}
    <select class="form-select form-select-sm" style="width:8rem; margin-right: 10px;" name="keywords">
      {% for species in breedsInDataBase %}
      <option value="" selected disabled hidden>依品種搜尋</option>
      <option>{{species.breed}}</option>
      {% endfor %}
    </select>
    <button id="searchBtn" class="btn me-5"type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16"> <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/> </svg></button> 
  </form>
  {% for item in adopts %}
  <div class="col-md-4 ">
      <div class="profile-card-2">
        <a class="button" href="#popUp{{item.id}}">
        {% if item.picUpload %}
          <img src="{{ item.picUpload.url }}" class="img img-fluid">
        {% else %}
          <img src="{{ item.pic }}" class="img img-fluid">
        {% endif %}
        <div class="profile-name">{{ item.breed }}</div>
        <div class="profile-username">{{ item.location }}</div>
        </a>
      </div>
  </div>
  <div id="popUp{{item.id}}" class="popUpOverlay">
    <div class="popUp d-flex align-items-center justify-content-around">
      <a class="close" href="#">&times;</a>
      <div class="popUpPic">
        {% if item.picUpload %}
          <img src="{{ item.picUpload.url }}" class="img img-fluid">
        {% else %}
          <img src="{{ item.pic }}" class="img img-fluid">
        {% endif %}
      </div>
      <div class="popUpInfo" style="padding-left: 1rem;">
        <ul>
          <li><i class="fas fa-paw"></i> 品種  ：  {{ item.breed }}</li>
          <li><i class="fas fa-paw"></i> 性別  ：  {{ item.sex }}</li>
          <li><i class="fas fa-paw"></i> 體型  ：  {{ item.size }}</li>
          <li><i class="fas fa-paw"></i> 年紀  ：  {{ item.age }}</li>
          <li><i class="fas fa-paw"></i> 是否已施打結紮  ：  {{ item.ligation }}</li>
          <li><i class="fas fa-paw"></i> 是否已施打疫苗  ：  {{ item.vaccine }}</li>
          <li><i class="fas fa-paw"></i> 所在地  ：  {{ item.location }}</li>
        </ul>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
</div>
<div id="pageSection" class="mt-3">
<ul class="pagination justify-content-center">
{% if adopts.has_previous%}
  <li class="page-item"><a style="margin-left: 1rem;color:	#B89886 !important;" href="?page=1">&laquo </a></li>
  <li class="page-item"><a style="margin: 0 1rem; color:	#B89886 !important;" href="?page={{adopts.previous_page_number}}">&lt</a></li>
{% endif %}
<li id="pgCenter"class="page-item disabled"><strong>{{adopts.number}}</strong> <span style="font-size: small;"> of {{adopts.paginator.num_pages}}</span></li>
{% if adopts.has_next%}
  <li class="page-item"><a style="margin-left: 1rem;color:	#B89886 !important;"href="?page={{adopts.next_page_number}}">&gt</a></li>
  <li class="page-item"><a style="margin-left: 1rem;color:	#B89886 !important;"href="?page={{adopts.paginator.num_pages}}">&raquo</a></li>
{% endif %}
<br/>
</ul>
</div>
{% endblock %}

templates/analysis.html
{% extends "base.html" %}
{% block content %}
    {% with ''|center:5 as range %}
    <!-- Swiper -->
    <div class="swiper-container mySwiper mt-3" >
        <div class="swiper-wrapper" style="background-color: #000;">
            {% for _ in range %}
            <div class="swiper-slide swiperNum{{ forloop.counter }}" id="twoPics">
                <img src="/static/ana/123.png">
            </div>
            {% endfor %}
        </div>
        <div class="swiper-pagination" style="background-color: #000;"></div>
    </div>
    <div class="swiper-button-next" style="padding: 0 2rem 0 0;"></div>
    <div class="swiper-button-prev" style="padding: 0 0 0 2rem;"></div>
    <div class="swiper-scrollbar"></div>
    {% endwith %} 
{% endblock %}

templates/analysisBreed.html
{% extends "base.html" %}
{% block content %}
    {% with ''|center:14 as range %}
    <!-- Swiper -->
   <div class="swiper-container mySwiper mt-3" >
    <div class="swiper-wrapper" style="background-color: #000;">
        {% for _ in range %}
        <div class="swiper-slide">
            <img src="/static/anaBreed/{{ forloop.counter }}.png" alt="banner.png">
        </div>
        {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
    </div>
    <div class="swiper-button-next" style="padding: 0 13rem 25rem 0;"></div>
    <div class="swiper-button-prev" style="padding: 0 0 25rem 13rem;"></div>
    {% endwith %} 
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/styles.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/style2.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/animal.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/bs.css' %}">
  <link rel="shortcut icon" type="image/x-icon" href="https://favicon-generator.org/favicon-generator/htdocs/favicons/2022-08-02/b07faee1ff9a4ce62db5047947d07f62.ico.png" />
  <title>動物領養 / 協尋</title>
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,500,500i,700|Barriecito" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css'>
  
  <script src="https://kit.fontawesome.com/72128276b1.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

  <script>
    $(document).ready(function(){
      var header = document.getElementById("myHeader");
      var sticky = header.offsetTop;
      var count = 3; 
      var redirect = "/"; 

      function countDown(inputUrl) {
        var timer = document.getElementById("timer"); 
        if (inputUrl!==undefined){
          redirect = inputUrl;
        }
        if (count > 0) {
          count--;
          timer.innerHTML = "倒數" + count + "秒跳轉頁面..."; 
          setTimeout("countDown()", 1000);
        } else {
          window.location.href = redirect;
        }
      }
      if (document.location.search.match(/type=embed/gi)) {
        window.parent.postMessage("resize", "*");
      }
      window.onscroll = function() {myFunction()};
      function myFunction() {
        if (window.pageYOffset > sticky) {
          header.classList.add("sticky");
        } else {
          header.classList.remove("sticky");
        }
      }
      $( "#id_picUpload" ). addClass( 'form-control');
        //Swiper
      var swiper = new Swiper(".mySwiper", {
        loop:true,
        pagination: {
        el: ".swiper-pagination",
        dynamicBullets: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
      });
  });
  </script>
</head>
<body style="height: 500px;" >
  <div id="parallax-world-of-ugg">
      {% include "header.html" %}
      {% block content %} {% endblock %}
  </div>
      {% include "footer.html" %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

templates/fancyCard.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="row">
  <div class="col-md-4">
  <h4 class="text-center"><strong>STYLE 1</strong></h4>
  <hr>
  <div class="profile-card-2"><img src="http://envato.jayasankarkr.in/code/profile/assets/img/profile-2.jpg" class="img img-responsive">
      <div class="profile-name">JOHN DOE</div>
      <div class="profile-username">@johndoesurname</div>
      <div class="profile-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a></div>
  </div>
</div>

<div class="col-md-4">
  <h4 class="text-center"><strong>STYLE 2</strong></h4>
  <hr>
  <div class="profile-card-6"><img src="http://envato.jayasankarkr.in/code/profile/assets/img/profile-6.jpg" class="img img-responsive">
      <div class="profile-name">JOHN
          <br>DOE</div>
      <div class="profile-position">Lorem Ipsum Donor</div>
      <div class="profile-overview">
          <div class="profile-overview">
              <div class="row text-center">
                  <div class="col-xs-4">
                      <h3>1</h3>
                      <p>Rank</p>
                  </div>
                  <div class="col-xs-4">
                      <h3>50</h3>
                      <p>Matches</p>
                  </div>
                  <div class="col-xs-4">
                      <h3>35</h3>
                      <p>Goals</p>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
  <div class="col-md-4">
  <h4 class="text-center"><strong>STYLE 3</strong></h4>
  <hr>
  <div class="profile-card-4 text-center"><img src="http://envato.jayasankarkr.in/code/profile/assets/img/profile-4.jpg" class="img img-responsive">
      <div class="profile-content">
          <div class="profile-name">John Doe
              <p>@johndoedesigner</p>
          </div>
          <div class="profile-description">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.</div>
          <div class="row">
              <div class="col-xs-4">
                  <div class="profile-overview">
                      <p>TWEETS</p>
                      <h4>1300</h4></div>
              </div>
              <div class="col-xs-4">
                  <div class="profile-overview">
                      <p>FOLLOWERS</p>
                      <h4>250</h4></div>
              </div>
              <div class="col-xs-4">
                  <div class="profile-overview">
                      <p>FOLLOWING</p>
                      <h4>168</h4></div>
              </div>
          </div>
      </div>
  </div>
</div>
</div>
</div>
{% endblock %}

templates/footer.html
<footer class="flex-rw mt-5 p-2">
  <section class="footer-social-section flex-rw">
      <span class="footer-social-overlap footer-social-connect">
      CONNECT <span class="footer-social-small">with</span> US
    </span>
      <span class="footer-social-overlap footer-social-icons-wrapper">
      <a href="#" class="generic-anchor" title="Github"><i class="fa fa-github"></i></a>
    </span>
  </section>
</footer>

templates/header.html
<section>
  <div class="title" id="myHeader">
    <h1 style="font-weight:100 !important;">Team 4</h1>
    <nav role="navigation" class="primary-navigation">
      <ul>
        <li><a href="/index/">首頁</a></li>
        <li><a href="/adoptPets/">領養專區</a></li>
        <li><a href="/lostPets/">走失協尋</a></li>
        <li><a href="#">分析 &dtrif;</a>
          <ul class="dropdown">
            <li><a href="/analysis/">..1</a></li>
            <li><a href="/analysisBreed/">..2</a></li>
          </ul>
        </li>
        <li><a href="/dogBreed/">品種辨識</a></li>
        <li><a href="#">我要刊登 &dtrif;</a>
          <ul class="dropdown">
            <li><a href="/upload/">領養資訊</a></li>
            <li><a href="/uploadLost/">走失協尋</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</section>

templates/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <!-- <base href="/"> -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/styles.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/style2.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/animal.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/bs.css' %}">
  <link rel="shortcut icon" type="image/x-icon" href="https://favicon-generator.org/favicon-generator/htdocs/favicons/2022-08-02/b07faee1ff9a4ce62db5047947d07f62.ico.png" />
  <title>動物領養 / 協尋</title>
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,500,500i,700|Barriecito" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css'>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script>window.console = window.console || function(t) {};</script>
  <script>
  if (document.location.search.match(/type=embed/gi)) {
    window.parent.postMessage("resize", "*");
  }
  </script>
</head>
<body>
  <div id="parallax-world-of-ugg">
    <!-- <section>
      <div class="title" style="padding:20px;">
        <h3>🐶🐱</h3>
        <h1>Team 4</h1>
      </div>
    </section> -->
    
    <section>
        <div class="parallax-one">
          <h2>Team 4</h2>
        </div>
    </section>
    
    <section>
      <div class="block">
        <p><span class="first-character sc">A</span>.</p>
        <ul class="feed">
          <li class="feed__item"><a class="arrowLink" href="/adoptPets">doption 認養專區<i class="arrowLink__icon"></i></a></li>
        </ul>
        <p class="line-break margin-top-10"></p>
      </div>
    </section>
    
    <section>
      <div class="parallax-two">
        <h2>  </h2>
      </div>
    </section>
    
    <section>
      <div class="block">
        <p><span class="first-character sc">L</span>.</p>
        <ul class="feed">
          <li class="feed__item"><a class="arrowLink" href="/adoptPets">ost 走失協尋<i class="arrowLink__icon"></i></a></li>
        </ul>
        <p class="line-break margin-top-10"></p>
      </div>
    </section>
    
    <section>
      <div class="parallax-three">
        <h2>  </h2>
      </div>
    </section>
    
    <section>
      <div class="block">
        <p><span class="first-character sc">B</span>.</p>
        <ul class="feed">
          <li class="feed__item"><a class="arrowLink" href="/adoptPets">reed 品種辨識<i class="arrowLink__icon"></i></a></li>
        </ul>
        <p class="line-break margin-top-10"></p>
      </div>
    </section>

    </div>
</body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

templates/lostPets.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
  <div class="row align-items-center">
    <form action="{% url 'lostData' %}" class="d-flex mt-2 justify-content-end" method="POST">
      {% csrf_token %}
      <select class="form-select form-select-sm" style="width:8rem; margin-right: 10px;" name="keywords">
        {% for species in speciesInDataBase %}
        <option value="" selected disabled hidden>依品種搜尋</option>
        <option>{{species.species}}</option>
        {% endfor %}
      </select>
      <button id="searchBtn" class="btn me-5" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16"> <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/> </svg></button> 
    </form>
  {% for item in losts %}
  <div class="col-md-4 ">
    <div class="profile-card-2">
      <a class="button" href="#popUp{{item.id}}">
      {% if item.picUpload %}
        <img src="{{ item.picUpload.url }}" class="img img-fluid">
      {% else %}
        <img src="{{ item.pet_jpg }}" class="img img-fluid">
      {% endif %}      
      <div class="profile-name">{{ item.name }}</div>
      <div class="profile-username">{{ item.area }}</div>
      </a>
    </div>
  </div>
  <div id="popUp{{item.id}}" class="popUpOverlay">
    <div class="popUp d-flex align-items-center justify-content-around">
      <a class="close" href="#">&times;</a>
      <div class="popUpPic">
        {% if item.picUpload %}
          <img src="{{ item.picUpload.url }}" class="img img-fluid">
        {% else %}
          <img src="{{ item.pet_jpg }}" class="img img-fluid">
        {% endif %}
      </div>
      <div class="popUpInfo" >
        <ul>
          <li><i class="fas fa-paw"></i> 姓名  ：  {{ item.name }}</li>
          <li><i class="fas fa-paw"></i> 品種  ：  {{ item.species }}</li>
          <li><i class="fas fa-paw"></i> 性別  ：  {{ item.gender }}</li>
          <li><i class="fas fa-paw"></i> 體型  ：  {{ item.body }}</li>
          <li><i class="fas fa-paw"></i> 年紀  ：  {{ item.age }}</li>
          <li><i class="fas fa-paw"></i> 走失日期  ：  {{ item.lostdate }}</li>
          <li><i class="fas fa-paw"></i> 走失地  ：  {{ item.area }}</li>
          <li><i class="fas fa-paw"></i> 聯絡人  ：  林小姐 </li>
          <li><i class="fas fa-paw"></i> 聯絡電話  ：  0985021433</li>
        </ul>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
</div>
<div id="pageSection">
  <ul class="pagination justify-content-center">
  {% if losts.has_previous%}
    <li class="page-item"><a style="margin-left: 1rem;color:	#B89886 !important;" href="?page=1">&laquo </a></li>
    <li class="page-item"><a style="margin: 0 1rem; color:	#B89886 !important;" href="?page={{losts.previous_page_number}}">&lt</a></li>
  {% endif %}
  <li id="pgCenter"class="page-item disabled"><strong>{{losts.number}}</strong> of {{losts.paginator.num_pages}}</li>
  {% if losts.has_next%}
    <li class="page-item"><a style="margin-left: 1rem;color:	#B89886 !important;"href="?page={{losts.next_page_number}}">&gt</a></li>
    <li class="page-item"><a style="margin-left: 1rem;color:	#B89886 !important;"href="?page={{losts.paginator.num_pages}}">&raquo</a></li>
  {% endif %}
  <br/>
  </ul>
</div>
{% endblock %}

templates/upload.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid d-flex justify-content-center">
  <div style="padding:5rem 5rem 0 0">
    <h1 style="color: #72626C; border-bottom: 5px solid #EED1CC;">領養資訊</h1>
  </div>
  <div class="row align-items-center">
  {% if submitted %}
      <div class="mt-5 align-items-center justify-content-center" > 
        <h1>🎉  刊登成功  🎊</h1>
        <h3 id="timer" class="mt-5 justify-content-center">
          <script type="text/javascript">
            countDown("../adoptPets/?page={{adopts.paginator.num_pages}}");
          </script>
        </h3>
      </div>
      <!-- <meta http-equiv="refresh" content="3;url=../adoptPets/?page={{adopts.paginator.num_pages}}" /> -->
  {% else %}
    <form action="{% url 'upload' %}" class="mt-2 justify-content-center" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p}}
      <input type="submit" value="送出" class="btn btn-secondary mt-3" style="background:#DFBFB2;border:none;">
    </form>
  {% endif %}
  </div>
</div>
{% endblock %}

templates/uploadLost.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid d-flex justify-content-center">
  <div style="padding:5rem 5rem 0 0">
    <h1 style="color: #72626C; border-bottom: 5px solid #EED1CC;">走失協尋</h1>
  </div>
  <div class="row align-items-center">
  {% if submitted %}
    <div class="mt-5 align-items-center justify-content-center" > 
      <h1>🎉  刊登成功  🎊</h1>
      <h3 id="timer" class="mt-5 justify-content-center">
        <script type="text/javascript">
          countDown("../lostPets/?page={{losts.paginator.num_pages}}");
        </script>
      </h3>
    </div>
  {% else %}
    <form action="{% url 'uploadLost' %}" class="mt-2 justify-content-center" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p}}
      <input type="submit" value="送出" class="btn btn-secondary mt-3" style="background:#DFBFB2;border:none;">
    </form>
  {% endif %}
  </div>
</div>
{% endblock %}